notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: EGhkY68OiamO40fATGmXieV/WKNlIO5Z5JJx2SMqY8IkqNVDxyevk7ZTnSEsRdGsnf6YhnQHBEmT24912icFzzMyyhffWW/93XZIWWhtylv65YzrrTBU+q0iezggfSABb/9/aNb/Mvknx5Edf77Q3r+9eDKBuu0uQ58DM560ctw1pUXt+EYxE8B1RhDhXuM9Y2EBlBH34t/DBenX9w1fXvxdooCS/ycP0AFTuHn7dwrLScGLExO55efjTmtfsY3EISuq+zOEpPxbctj+OZW6oSezED7Q/txQ+BVXV0lLJQ94YaGU+WCh3Zjt7BNb3Gtu+1FcEv6rlxPW0FHIlc+Qdf4hl3AiJ4ZEdr7kEjDbselt7RrFoYghRy5EUnQLX3xQBkAysjCprjFZ23+b7k2TIH/e6pa6E533KCV9Sl94CvSjgUBWb+n2+fCK3zM1UoJFqT3PGe+5BclrcUmBqXaUcl74Plyp2typz/uyz/tlCMpCX5pRBn+PcGroGXtdLMZTvaV5EuR8vrqohQ4KAGpXcxNdO/G66PAVb2Z1n6Ec5r+uYHl4eCFMjKlLrXtzYgdKBhB583tymYxEuUiiCMCxf0VpUS5PySH+1zuz1j3HzQ46vFmbAKbwTHa8Afb7qB7k1pdjyvE3FTm3vVDvWOkrL6cYni086qOROOzNYUEfQXA=
  api_key:
    secure: hgxoyGB7ucT3Fln6z6AhqNGO2tBCjYXX9gMWFxdbn1DsXFlGSSM5MBPG4WNJSstBT+CM1R1zxrOB5qn+3kS6RrNIs216JCCl9vT5Ko30Ja8XkGDwLXfr09Er2GKnl+3PPR1f9PVc//Pvt9LWecYs3LJj5qMQcLGtI+M6M9n7MyAI97LKlqUKl/WnFUAGrTITNS0UJV//vFeJjxG/enTn1/cH/XaDMw4Z7sT/af6iOcTfR4HaRl65CIbdPeVotOgXvPK+CB06zE5y+rI5Y/Xc3N4vZYCwV7UGigYF/c9x43RunfHBcM3BagjWfJoSzpm8wy/Buo48FNIwqvL5rZ9+maHEX6YsG5Aefd9GQKy83vHP5MHFWOnjuuuNAMX2XxnqEGJmfRq+BhsJUiYNmGmvvI8ClzvKtNhOtF26TIlxYSA0ukZg0caXPyQM+vwTx+vN5Qhm6BuJQPoTc0T1e/Nga9nOpeSetkmIAi1iysnHuOrRnq7vMza/WZZI/d1Ct4tjdaK/1zDafz0tDw8IQ+brrKed9VH4q/HTq861o62wkJgvTKWFRITKV5/Jtz8wSnu+lVB074cPYroc1v1hgUPm3PJukROVykOUVUFFXNANddmD4f2wDyEUHAez7pC3w7eXhGSZVSYuOClYFnPntn83LrhPal5pBDJ5ujajbEgq1gc=
  on:
    tags: true
